more regression tests

diff --git a/examples/atlas_regressionTest b/examples/atlas_regressionTest
--- a/examples/atlas_regressionTest
+++ b/examples/atlas_regressionTest
@@ -2,25 +2,21 @@
 
 compare() {
     echo "Comparing reference ATLAS-files to new ones"
+    local differs=""
     for a in ATLAS_*; do
-	if [[ $a == *.bai ]]; then continue; fi
+	[[ $a == *.bai ]] && continue
 	if [[ $a == *.bam ]]; then
 	    command -v samtools > /dev/null || continue
-
-	    if ! diff -q <(samtools view $a) <(samtools view ../${fo}_ref/$a); then
-		differs=true
-	    fi
+	    ! diff -q <(samtools view $a) <(samtools view ../${fo}_ref/$a) && differs=true
 	fi
-	if ! diff -q $a ../${fo}_ref/$a; then
-	    differs=true
-	fi
+	! diff -q $a ../${fo}_ref/$a &&  differs=true
     done
-    if [[ ! $differs ]]; then
-	echo "All files are identical"
-    fi
+    [[ $differs ]] && return 1
+    echo "All files are identical"
 }
 
-for f in *.sh; do (
+err=0
+for f in *.sh; do
     fo=${f%.sh}
     echo "Regresision Test: $fo"
     if [[ ! -d ${fo}_ref ]]; then
@@ -28,6 +24,7 @@ for f in *.sh; do (
 	mkdir -v ${fo}_ref
 	cd ${fo}_ref
 	bash ../$f > out 2> eout
+	[[ -s eout ]] && echo "Reference simulation of $fo ended with errors"; cat eout
     else
 	echo "Found reference ATLAS-files in folder ${fo}_ref"
 	if [[ ! -d ${fo}_new ]]; then
@@ -35,12 +32,16 @@ for f in *.sh; do (
 	    mkdir -v ${fo}_new
 	    cd ${fo}_new
 	    bash ../$f > out 2> eout
+	    [[ -s eout ]] && echo "New simulation of $fo ended with errors"; cat eout
 	else
 	    echo "Found new ATLAS-files in folder ${fo}_new"
 	    cd ${fo}_new
 	fi
 
-	compare
+	! compare && err=1
     fi
+    cd ..
     echo
-) done
+done
+
+exit $err
